# netlify.toml

[build]
  command = "npm run netlify-build"
  publish = "dist"

[[redirects]]
  from = "/storybook"
  to = "/storybook/index.html"
  status = 200

[[redirects]]
  from = "/storybook/*"
  to = "/storybook/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
