# Общие настройки
[build]
  command = "npm run build"
  publish = "dist"

# === Основной проект: frtvt-marketplace ===
[context.production]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "mkdir -p dist && echo 'Skipping deploy preview' && exit 0"
  publish = "dist"

[context.branch-deploy]
  command = "mkdir -p dist && echo 'Skipping branch deploy' && exit 0"
  publish = "dist"

# === Storybook-проект: frtvt-marketplace-storybook ===
[context."branch=storybook"]
  command = "npm run build-storybook"
  publish = "storybook-static"

  [[context."branch=storybook".redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
