# netlify.toml

[build]
  command = "npm run netlify-build"
  publish = "dist"
git add netlify.toml
git commit -m "fix(netlify): add redirect for /storybook root path"
git push

[[redirects]]
  from = "/storybook"
  to = "/storybook/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/storybook/*"
  to = "/storybook/index.html"
  status = 200
  force = true
