[build]
  command = "npm run build"
  publish = "dist"

# Production build (merge into main)
[context.production]
  command = "npm run build"
  publish = "dist"

# Skip builds for Deploy Previews
[context.deploy-preview]
  command = "echo \"Skipping deploy preview\" && exit 0"
  publish = "dist"

# Skip builds for all other branches by default
[context.branch-deploy]
  command = "echo \"Skipping branch deploy\" && exit 0"
  publish = "dist"

# Run Storybook build on the `storybook` branch
[context."branch=storybook"]
  command = "npm run build-storybook"
  publish = "storybook-static"
