name: Deploy Storybook to 'storybook' branch

on:
  push:
    branches:
      - main

# Разрешаем GitHub Actions писать в репозиторий
permissions:
  contents: write

jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    # Переопределяем также на уровне джоба
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Чтобы GITHUB_TOKEN мог пушить
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to storybook branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Переключаем/создаём ветку storybook
          git checkout -B storybook

          # Добавляем все изменения (в т.ч. storybook-static) к коммиту
          git commit --all -m "chore(storybook): deploy storybook [auto]" || echo "Nothing to commit"

          # Пушим в ветку storybook с помощью GITHUB_TOKEN
          git push -f --set-upstream https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }} storybook
пш
